name: Build Nuitka Binary
on: 
  push:
    branches:
      - main
    paths:
      - 'BierAmpel.py'
      - 'requirements.txt'
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    # Use the native ARM64 runner
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          sudo apt-get install python3-dev
          pip install nuitka
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone \
          --include-package=gpiozero \
          --include-module=gpiozero.pins.lgpio \
          --plugin-enable=pyside2 --output-dir=packages \
          --output-filename=BierAmpel-arm64rpi5 \
          --onefile BierAmpel.py

      - name: Make binary executable
        run: |
          chmod +x packages/BierAmpel-arm64rpi5

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: rpi-binary
          path: packages/BierAmpel-arm64rpi5

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rpi-binary
      - uses: softprops/action-gh-release@v2
        with:
          files: BierAmpel-arm64rpi5